language: generic

matrix:
  include:
    - os: linux
      sudo: false
      addons:
        apt:
          packages:
            - libgmp-dev
    - os: osx
      sudo: false
      osx_image: xcode7.3 # upgrades clang from 6 -> 7

before_install:
  # Download and unpack the stack executable
  - |
    set -e
    mkdir -p ~/.local/bin
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      STACK_URL="https://www.stackage.org/stack/osx-x86_64"
      travis_retry curl -L $STACK_URL \
        | tar xz --strip-components=1 -C ~/.local/bin
    else
      STACK_URL="https://www.stackage.org/stack/linux-x86_64"
      travis_retry curl -L $STACK_URL \
        | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  -  export PATH=$HOME/.local/bin:$PATH

script:
  - stack --no-terminal --install-ghc test

cache:
  directories:
  - $HOME/.stack
