resolver: lts-5.12
packages:
- '.'
- location:
    git: https://github.com/albertov/spatial-reference.git
    commit: f4deaea7abe752105275abfc61338e0d9cfe7522
  extra-dep: true
extra-deps:
- mime-0.4.0.2
